name: CI/CD-Pipeline
on:
  push:
    branches: ["main"]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # This specifically tells GitHub to stop warning you about Node 20
          token: ${{ github.token }} 
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

      - name: Build & Test Locally
        run: |
          docker build -t devops-demo .
          docker run -d -p 8080:80 --name test devops-demo
          sleep 5
          curl -f http://localhost:8080
          docker rm -f test

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Using sudo ensures Docker and RM commands don't fail due to permissions
            cd /home/ec2-user
            sudo rm -rf demo-app
            git clone https://github.com/ujwalakula-p99soft/Devops-Demo.git
            cd demo-app
            sudo docker rm -f nginx-container || true
            sudo docker build -t nginx-devops-demo .
            sudo docker run -d -p 80:80 --name nginx-container nginx-devops-demo
